name: Deploy to Firebase Hosting (Development)
on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Web
        run: |
          flutter build web --release \
            --dart-define=ENVIRONMENT=dev \
            --dart-define=FIREBASE_DEV_WEB_API_KEY="${{ secrets.FIREBASE_DEV_WEB_API_KEY }}" \
            --dart-define=FIREBASE_DEV_WEB_APP_ID="${{ secrets.FIREBASE_DEV_WEB_APP_ID }}" \
            --dart-define=FIREBASE_DEV_WEB_MEASUREMENT_ID="${{ secrets.FIREBASE_DEV_WEB_MEASUREMENT_ID }}" \
            --dart-define=FIREBASE_DEV_ANDROID_API_KEY="${{ secrets.FIREBASE_DEV_ANDROID_API_KEY }}" \
            --dart-define=FIREBASE_DEV_ANDROID_APP_ID="${{ secrets.FIREBASE_DEV_ANDROID_APP_ID }}" \
            --dart-define=FIREBASE_DEV_IOS_API_KEY="${{ secrets.FIREBASE_DEV_IOS_API_KEY }}" \
            --dart-define=FIREBASE_DEV_IOS_APP_ID="${{ secrets.FIREBASE_DEV_IOS_APP_ID }}" \
            --dart-define=FIREBASE_DEV_MESSAGING_SENDER_ID="${{ secrets.FIREBASE_DEV_MESSAGING_SENDER_ID }}" \
            --dart-define=FIREBASE_DEV_PROJECT_ID="${{ secrets.FIREBASE_DEV_PROJECT_ID }}" \
            --dart-define=FIREBASE_DEV_AUTH_DOMAIN="${{ secrets.FIREBASE_DEV_AUTH_DOMAIN }}" \
            --dart-define=FIREBASE_DEV_STORAGE_BUCKET="${{ secrets.FIREBASE_DEV_STORAGE_BUCKET }}" \
            --dart-define=IOS_BUNDLE_ID="${{ secrets.IOS_BUNDLE_ID }}"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          fireBaseServiceAccount: ${{ secrets.MAYPOLE_FIREBASE_SERVICE_ACCOUNT_DEV }}
          projectId: maypole-flutter-dev
          version: dev
          channelId: live